# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4aab0213deb9daf3e14be71d0c8f55a4eb6442ddcf7a246685ca7e142a64cc66aa6bc235ad15935ac246d5320d4dd9908f3d82ca7c8c39ff595c3fa704af4c0

test:
  secret_key_base: 52858a9843cb3cc062faade0f391fddf6de529478c000dea95810d2b6ee8cbeb35a2fd70521bdf85d3bf8d409da0c77c96ec80b486796e5591a60b0e65d46f06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
